apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sparkel-vilkarsproving
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 6
    cpuThresholdPercentage: 75
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/azure
        kvPath: /azuread/data/prod/creds/sparkel-vilkarsproving
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvsparkelvilkar
  env:
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
  - name: KAFKA_CONSUMER_GROUP_ID
    value: sparkel-vilkarsproving-v1
  - name: KAFKA_RAPID_TOPIC
    value: helse-rapid-v1
  - name: AZURE_TENANT_ID
    value: 62366534-1ec3-4962-8869-9b5535279d0b
  - name: STS_URL
    value: https://sts.adeo.no/SecurityTokenServiceProvider/
  - name: EGENANSATT_URL
    value: https://app.adeo.no/tpsws-aura/EgenAnsatt/v1
  - name: AAREG_BASE_URL
    value: https://modapp.adeo.no/aareg-services/api
